table 'Purchase Currency'
	lineageTag: 58235e0e-fa22-4f90-8aa5-400f369e9214

	column PC_ID
		dataType: int64
		formatString: 0
		lineageTag: 52cbb5b8-39ce-43ae-b7b0-78cf94b6327d
		summarizeBy: none
		sourceColumn: PC_ID

		annotation SummarizationSetBy = Automatic

	column 'Purchase Currency'
		dataType: string
		lineageTag: 2bd29086-e5ca-4606-b429-405959d34612
		summarizeBy: none
		sourceColumn: Purchase Currency

		annotation SummarizationSetBy = Automatic

	column PC
		dataType: string
		lineageTag: de0a35a1-777f-4b2d-a696-cf9b4a9d37b1
		summarizeBy: none
		sourceColumn: PC

		annotation SummarizationSetBy = Automatic

	partition 'Purchase Currency-a6beb576-e9ae-4c8d-b4d8-81c5bafb1b4e' = m
		mode: import
		queryGroup: DimensionsTables
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Asus\Downloads\Challenge-9-Data.xlsx"), null, true),
				    TradingData_Table = Source{[Item="TradingData",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TradingData_Table,{{"Reference", type text}, {"Est Load Date", type date}, {"Confirmed Load Date", type date}, {"Delivery Date", type date}, {"Grade", type text}, {"Unit Purchase Price", type number}, {"Purchase Currency", type text}, {"Unit Sales Price", Int64.Type}, {"Sale Currency", type text}, {"Supplier", type text}, {"Buyer", type text}, {"Est Weight", type number}, {"Haulier", type text}, {"Haulage Cost", type number}, {"Haulage Currency", type text}, {"Load PERNable", type text}, {"Total Supplier Weight", type number}, {"Total Buyer Weight", type number}, {"Account manager", type text}, {"Collection Type", type text}, {"Process flow stage", type text}, {"Customer Load Type", type text}, {"PRN Value per tonne", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Purchase Currency"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Alternate Rows" = Table.AlternateRows(#"Removed Duplicates",1,1,3),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Alternate Rows", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "PC_ID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"PC_ID", "Purchase Currency"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Reordered Columns", "PC", each if [Purchase Currency] = "(£) - Pound Sterling" then "British Pound" else if [Purchase Currency] = "($) - US Dollar" then "US Dollar" else if [Purchase Currency] = "(€) - Euro" then "Euro" else null),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"PC", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

