table Suppliers
	lineageTag: 3ab6f583-81ac-4026-8c99-4d673659e389

	column Supplier_ID
		dataType: int64
		formatString: 0
		lineageTag: 8e0ac6fb-01e4-4f79-b735-b0bd73694ff1
		summarizeBy: none
		sourceColumn: Supplier_ID

		annotation SummarizationSetBy = Automatic

	column Supplier
		dataType: string
		lineageTag: cfa37ccd-90c5-48bf-849c-5348443ba129
		summarizeBy: none
		sourceColumn: Supplier

		annotation SummarizationSetBy = Automatic

	partition Suppliers-ec308adc-b4b6-45bd-b91f-ccd543360c6c = m
		mode: import
		queryGroup: DimensionsTables
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Asus\Downloads\Challenge-9-Data.xlsx"), null, true),
				    TradingData_Table = Source{[Item="TradingData",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TradingData_Table,{{"Reference", type text}, {"Est Load Date", type date}, {"Confirmed Load Date", type date}, {"Delivery Date", type date}, {"Grade", type text}, {"Unit Purchase Price", type number}, {"Purchase Currency", type text}, {"Unit Sales Price", Int64.Type}, {"Sale Currency", type text}, {"Supplier", type text}, {"Buyer", type text}, {"Est Weight", type number}, {"Haulier", type text}, {"Haulage Cost", type number}, {"Haulage Currency", type text}, {"Load PERNable", type text}, {"Total Supplier Weight", type number}, {"Total Buyer Weight", type number}, {"Account manager", type text}, {"Collection Type", type text}, {"Process flow stage", type text}, {"Customer Load Type", type text}, {"PRN Value per tonne", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Supplier"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Supplier_ID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Supplier_ID", "Supplier"})
				in
				    #"Reordered Columns"

	annotation PBI_ResultType = Table

